[package]
name = "minictl"
version = "0.1.0"
edition = "2021"

[lib]
name = "minictl"
crate-type = ["cdylib"]

[features]
python = ["dep:pyo3"]

[dependencies]
pyo3 = { version = "0.23.4", optional = true, features = ["extension-module"] }
