class State:
    name: str
    variables: set[str]
    def __init__(self, name: str, variables: set[str]): ...
    def contains(self, var: str) -> bool: ...

class Model:
    def __init__(self, states: list[State], edges: dict[str, list[str]]) -> None: ...
    def get_state(self, which: str) -> State: ...
    def get_states(self) -> list[State]: ...
    def all(self) -> set[str]: ...
    def all_containing(self, var: str) -> set[str]: ...
    def all_except(self, names: set[str]) -> set[str]: ...
    def pre_e(self, names: set[str]) -> set[str]: ...
    def pre_a(self, names: set[str]) -> set[str]: ...
    def get_next(self, name: str) -> set[str]: ...
