class LTLFormula:
    def __init__(self, name: str, *args: LTLFormula) -> None: ...
    @staticmethod
    def parse(formula: str) -> LTLFormula: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...

class CTLFormula:
    def __init__(self, name: str, *args: CTLFormula) -> None: ...
    @staticmethod
    def parse(formula: str) -> CTLFormula: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
